repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: no-commit-to-branch
      args: [--branch, discovery]
      exclude: ^htmrl_env/
    - id: check-merge-conflict
      description: Prevent committing if a merge conflict is unresolved
    - id: check-yaml
      args: ["--unsafe"]
    - id: end-of-file-fixer
      exclude: \.(drawio|png)$
    - id: mixed-line-ending
      args: ["--fix=lf"]
    # - id: check-shebang-scripts-are-executable
  - repo: local
    hooks:
      - id: python-flake8
        name: Python Linter
        entry: ./lint.sh
        pass_filenames: false
        types: [python]
        language: system
        exclude: ^htmrl_env/
      - id: python-format
        name: Python Formatting
        entry: make format
        pass_filenames: false
        types: [python]
        language: system
        exclude: ^htmrl_env/
      - id: python-docstrings
        name: Python Docstring Checks
        entry: bash -c 'PYTHONPATH=src make lint-docs'
        pass_filenames: false
        types: [python]
        language: system
        exclude: ^(htmrl_env/|tests/)
