# Experimental environment for attempting NuPIC source builds on Windows
# This is not guaranteed to work; provided for advanced users.
name: nupic-src
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6.*
  - pip
  - cmake
  - git
  - swig
  - pkg-config
  - setuptools<60
  - wheel
  - numpy=1.18.5
  - pywin32
  - vs2015_runtime  # Helpful for some old binary deps
  - pip:
      - capnproto==0.6.1  # Historical dependency versions used by older builds (may vary)
      # - nupic.bindings  # Prefer building from source with matching nupic.core, not PyPI
