# Modern HTM (Hierarchical Temporal Memory) environment using htm.core
# htm.core supports newer Python versions (>=3.8 typically). This avoids legacy NuPIC Python 3.6 constraint.
#https://github.com/htm-community/htm.core

name: htmcore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.*  
  - pip
  - numpy
  - cmake
  - wheel
  - setuptools
  - pip:
      - tensorflow
      - torch
      - gymnasium[classic_control]
      - yfinance
      


# Create & test:
#   conda env create -f environment-htmcore.yml
#   conda activate htmcore
#   python -c "import htm; print('htm.core OK, version:', htm.__version__)"
