# Modern HTM (Hierarchical Temporal Memory) environment using htm.core
# htm.core supports newer Python versions (>=3.8 typically). This avoids legacy NuPIC Python 3.6 constraint.
name: htmcore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*  # Stable, broadly supported
  - pip
  - numpy
  - pybind11  # Helpful for native extension build sanity
  - cmake      # In case source build is needed
  - wheel
  - setuptools
  - pip:
      - htm.core  # Current maintained package

# Create & test:
#   conda env create -f environment-htmcore.yml
#   conda activate htmcore
#   python -c "import htm; print('htm.core OK, version:', htm.__version__)"
